### PR TITLE
Handles missing magnet link and added metadata timeout.

### PR DESCRIPTION
**Pull request by Zer0C001**
Handles missing magnet link and inability to get torrent metadata ( determined via a timeout ) by playing from webseed.
Also shows a notification while verifying downloaded data.

### CODE REVIEW

**Comment by Zer0C001** [comment]
@jasonfrancis 
Is there a problem with this PR ? Seems that the issues it solves are getting more frequent.

**Comment by jasonfrancis** [comment]
@Zer0C001 I had a lot of trouble when I was testing this - it seemed to be with the 
```
for stdout_line in iter(webTorrentClient.stdout.readline,b''):
```
section, but I think was was down to an issue in webtorrent-hybrid itself when running on certain varieties of linux.

I got too busy at my day job to dig into it any further.

I'll go ahead and merge this, and we can make fixes for any clients it causes trouble for.

**Comment by Zer0C001** [comment]
Interesting, I'm getting a lot of timeouts when fetching torrent metadata lately, but it also happens when running webtorrent-hybrid.

**Comment by jasonfrancis** [comment]
I'm also getting those timeouts when using webtorrent-hybrid I can't figure out if:
* There's a problem with newer versions of webtorrent-hybrid?
* There's a problem with Bitchute's webtorrent implementation?
  * Or maybe it's outdated?
* Or maybe Bitchute is quietly giving up on webtorrent for most videos and just serving the video via HTTP.

It could be a lot of things, but it does mean we end up playing from a webseed 9 times out of 10.

**Comment by Zer0C001** [comment]
I'd bet on option 3 "Bitchute is quietly giving up on webtorrent", they don't seem to be using webtorrent in the browser anymore and directly uploaded videos don't even have magnet links.

**Pull request merged**
